import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Material from '@angular/material';



@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    Material.MatSidenavModule,
    Material.MatExpansionModule,
    Material.MatMenuModule,
    Material.MatDividerModule,
    Material.MatListModule,
    Material.MatSortModule,
    Material.MatDialogModule,
    Material.MatProgressSpinnerModule, 
    Material.MatCardModule,
    Material.MatSlideToggleModule,
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatRadioModule,
    Material.MatSelectModule,
    Material.MatCheckboxModule,
    Material.MatDatepickerModule,
    Material.MatNativeDateModule,
    Material.MatButtonModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatIconModule,
    Material.MatSnackBarModule,
    Material.MatStepperModule,
    Material.MatTabsModule,
  ],
  exports: [
    Material.MatSidenavModule,
    Material.MatExpansionModule,
    Material.MatMenuModule,
    Material.MatDividerModule,
    Material.MatListModule,
    Material.MatSortModule,
    Material.MatDialogModule,
    Material.MatProgressSpinnerModule, 
    Material.MatCardModule,
    Material.MatSlideToggleModule,
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatRadioModule,
    Material.MatSelectModule,
    Material.MatCheckboxModule,
    Material.MatDatepickerModule,
    Material.MatNativeDateModule,
    Material.MatButtonModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatIconModule,
    Material.MatSnackBarModule,
    Material.MatStepperModule,
    Material.MatTabsModule,
  ],
})
export class MaterialModule { }
